name: Build and Deploy

on:  
  pull_request:
    types: [opened, reopened]

jobs:
  Build_application:
    runs-on: ubuntu-latest

    env:
      NAME_BRANCH: ${{ github.head_ref }}
 
    steps:
    
      - name: Print name branch
        run: "echo NAME_BRANCH: ${NAME_BRANCH}"

      - name: Find specific branch patterns
        run: |
          import re
          name_branch = str(${{ env.NAME_BRANCH }}).lower()
          x = re.findall("alpha|beta|prerelease", name_branch)
          prerelease = (x[0])
          print(prerelease)
          if x:
            print("Yes, there is at least one match!")
          else:
            print("No match")
        shell: python
