name: Build and Deploy

on:  
  pull_request:
    types: [opened, reopened]

jobs:
  Build_application:
    runs-on: ubuntu-latest
    steps:
    
      - name: echo a string
        env:
          NAME_BRANCH: ${{ github.head_ref }}
        run: |
          echo "NAME_BRANCH: ${NAME_BRANCH}"

# echo "GITHUB_REPO_ACTOR: ${GITHUB_REPO_ACTOR}"
          # echo "GITHUB_REPO_NAME: ${GITHUB_REPO_NAME}"          
          # echo "HOME: ${HOME}"
          # echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          # echo "GITHUB_ACTION: ${GITHUB_ACTION}"
          # echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          # echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          # echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          # echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          # echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          # echo "GITHUB_SHA: ${GITHUB_SHA}"
          # echo "GITHUB_REF: ${GITHUB_REF}"
          # echo "WF_ENV: ${WF_ENV}"
          # echo "JOB_ENV: ${JOB_ENV}"
          # echo "STEP_ENV: ${STEP_ENV}" 