name: a

# Triggers:
on:
  push:
  # pull_request:
  #   types: [closed]

jobs:
  # This workflow will run only if the PR is merged into master
    run-shell-commands:
      # if: github.event.pull_request.merged == true
      runs-on: ubuntu-latest
      steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python commands
        run: |
          import platform
          print(platform.processor())
        shell: python