name: Build and Deploy

on:
  # push:  
  pull_request:
    types: [opened, reopened]

jobs:
  Build_application:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: |
          echo "github.head_ref: ${{ github.head_ref }}"
          echo "NAME_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV