name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  Deploy_application:
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub Context
        run: echo '${{ toJSON(github) }}'