name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  Deploy_application:
    runs-on: ubuntu-latest

    steps:
      - name: Getting the Source Branch Suffix of the Pull Request Merged
        run: |
          echo '${{ toJSON(github) }}' > github.json
        
      - name: Create an Environment Variable with the Source Branch Suffix
        run: |
          cat github.json | jq '.event.commits[-1].message' | jq 'split("/")' | jq --raw-output .[1]

      - name: Print Source Branch Suffix
        id: teste-workflow
        run: |
          echo "SOURCE_BRANCH_SUFFIX=$(cat github.json | jq '.event.commits[-1].message' | jq 'split("/")' | jq --raw-output .[1])" >> $GITHUB_ENV

      - name: Print Source Branch Suffix
        run: |
          echo "SOURCE_BRANCH_SUFFIX: ${{ env.SOURCE_BRANCH_SUFFIX }}"


